/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconButtonLevelTypes, IconButtonTypeTypes, IconNameTypes, IconSizeTypes, SelectFlowTypes, SelectOptionType, TextButtonLevelTypes, TextButtonTypeTypes, TypoBodyLevelTypes, TypoHeadingLevelTypes, TypoHeadingTagTypes, TypoWeightTypes } from "./shared/types";
export namespace Components {
    interface EzpAuth {
        "clientID": string;
        "redirectURI": string;
    }
    interface EzpIcon {
        /**
          * Description...
         */
        "name": IconNameTypes;
        /**
          * Description...
         */
        "size": IconSizeTypes;
    }
    interface EzpIconButton {
        /**
          * Description...
         */
        "blank": boolean;
        /**
          * Description...
         */
        "disabled": boolean;
        /**
          * Description...
         */
        "href": string;
        /**
          * Description...
         */
        "icon": IconNameTypes;
        /**
          * Description...
         */
        "level": IconButtonLevelTypes;
        /**
          * Description...
         */
        "type": IconButtonTypeTypes;
    }
    interface EzpPrinterSelection {
        /**
          * Properties
         */
        "clientID": string;
        "redirectURI": string;
    }
    interface EzpPrinting {
        "clientid": string;
        "custom": boolean;
        "filename": string;
        "filetype": string;
        "fileurl": string;
        /**
          * Public methods
         */
        "open": () => Promise<void>;
        "redirecturi": string;
    }
    interface EzpProgress {
        /**
          * Status...
         */
        "status": string;
    }
    interface EzpSelect {
        /**
          * Description...
         */
        "icon": IconNameTypes;
        /**
          * Description...
         */
        "label": string;
        /**
          * Description...
         */
        "optionFlow": SelectFlowTypes;
        /**
          * Description...
         */
        "options": SelectOptionType[];
        /**
          * Description...
         */
        "placeholder": string;
        /**
          * Description...
         */
        "toggleFlow": SelectFlowTypes;
    }
    interface EzpTextButton {
        /**
          * Description...
         */
        "blank": boolean;
        /**
          * Description...
         */
        "disabled": boolean;
        /**
          * Description...
         */
        "href": string;
        /**
          * Description...
         */
        "level": TextButtonLevelTypes;
        /**
          * Description...
         */
        "type": TextButtonTypeTypes;
    }
    interface EzpTypoBody {
        /**
          * Description...
         */
        "level": TypoBodyLevelTypes;
        /**
          * Description...
         */
        "weight": TypoWeightTypes;
    }
    interface EzpTypoHeading {
        /**
          * Description...
         */
        "level": TypoHeadingLevelTypes;
        /**
          * Description...
         */
        "tag": TypoHeadingTagTypes;
        /**
          * Description...
         */
        "weight": TypoWeightTypes;
    }
}
declare global {
    interface HTMLEzpAuthElement extends Components.EzpAuth, HTMLStencilElement {
    }
    var HTMLEzpAuthElement: {
        prototype: HTMLEzpAuthElement;
        new (): HTMLEzpAuthElement;
    };
    interface HTMLEzpIconElement extends Components.EzpIcon, HTMLStencilElement {
    }
    var HTMLEzpIconElement: {
        prototype: HTMLEzpIconElement;
        new (): HTMLEzpIconElement;
    };
    interface HTMLEzpIconButtonElement extends Components.EzpIconButton, HTMLStencilElement {
    }
    var HTMLEzpIconButtonElement: {
        prototype: HTMLEzpIconButtonElement;
        new (): HTMLEzpIconButtonElement;
    };
    interface HTMLEzpPrinterSelectionElement extends Components.EzpPrinterSelection, HTMLStencilElement {
    }
    var HTMLEzpPrinterSelectionElement: {
        prototype: HTMLEzpPrinterSelectionElement;
        new (): HTMLEzpPrinterSelectionElement;
    };
    interface HTMLEzpPrintingElement extends Components.EzpPrinting, HTMLStencilElement {
    }
    var HTMLEzpPrintingElement: {
        prototype: HTMLEzpPrintingElement;
        new (): HTMLEzpPrintingElement;
    };
    interface HTMLEzpProgressElement extends Components.EzpProgress, HTMLStencilElement {
    }
    var HTMLEzpProgressElement: {
        prototype: HTMLEzpProgressElement;
        new (): HTMLEzpProgressElement;
    };
    interface HTMLEzpSelectElement extends Components.EzpSelect, HTMLStencilElement {
    }
    var HTMLEzpSelectElement: {
        prototype: HTMLEzpSelectElement;
        new (): HTMLEzpSelectElement;
    };
    interface HTMLEzpTextButtonElement extends Components.EzpTextButton, HTMLStencilElement {
    }
    var HTMLEzpTextButtonElement: {
        prototype: HTMLEzpTextButtonElement;
        new (): HTMLEzpTextButtonElement;
    };
    interface HTMLEzpTypoBodyElement extends Components.EzpTypoBody, HTMLStencilElement {
    }
    var HTMLEzpTypoBodyElement: {
        prototype: HTMLEzpTypoBodyElement;
        new (): HTMLEzpTypoBodyElement;
    };
    interface HTMLEzpTypoHeadingElement extends Components.EzpTypoHeading, HTMLStencilElement {
    }
    var HTMLEzpTypoHeadingElement: {
        prototype: HTMLEzpTypoHeadingElement;
        new (): HTMLEzpTypoHeadingElement;
    };
    interface HTMLElementTagNameMap {
        "ezp-auth": HTMLEzpAuthElement;
        "ezp-icon": HTMLEzpIconElement;
        "ezp-icon-button": HTMLEzpIconButtonElement;
        "ezp-printer-selection": HTMLEzpPrinterSelectionElement;
        "ezp-printing": HTMLEzpPrintingElement;
        "ezp-progress": HTMLEzpProgressElement;
        "ezp-select": HTMLEzpSelectElement;
        "ezp-text-button": HTMLEzpTextButtonElement;
        "ezp-typo-body": HTMLEzpTypoBodyElement;
        "ezp-typo-heading": HTMLEzpTypoHeadingElement;
    }
}
declare namespace LocalJSX {
    interface EzpAuth {
        "clientID"?: string;
        "onAuthCancel"?: (event: CustomEvent<MouseEvent>) => void;
        "onPrintShow"?: (event: CustomEvent<any>) => void;
        "redirectURI"?: string;
    }
    interface EzpIcon {
        /**
          * Description...
         */
        "name": IconNameTypes;
        /**
          * Description...
         */
        "size"?: IconSizeTypes;
    }
    interface EzpIconButton {
        /**
          * Description...
         */
        "blank"?: boolean;
        /**
          * Description...
         */
        "disabled"?: boolean;
        /**
          * Description...
         */
        "href"?: string;
        /**
          * Description...
         */
        "icon": IconNameTypes;
        /**
          * Description...
         */
        "level"?: IconButtonLevelTypes;
        /**
          * Description...
         */
        "type"?: IconButtonTypeTypes;
    }
    interface EzpPrinterSelection {
        /**
          * Properties
         */
        "clientID"?: string;
        /**
          * Description...
         */
        "onPrintCancel"?: (event: CustomEvent<MouseEvent>) => void;
        /**
          * Description...
         */
        "onPrintSubmit"?: (event: CustomEvent<MouseEvent>) => void;
        "redirectURI"?: string;
    }
    interface EzpPrinting {
        "clientid"?: string;
        "custom"?: boolean;
        "filename"?: string;
        "filetype"?: string;
        "fileurl"?: string;
        "redirecturi"?: string;
    }
    interface EzpProgress {
        /**
          * Status...
         */
        "status"?: string;
    }
    interface EzpSelect {
        /**
          * Description...
         */
        "icon"?: IconNameTypes;
        /**
          * Description...
         */
        "label"?: string;
        /**
          * Events
         */
        "onSelectToggle"?: (event: CustomEvent<any>) => void;
        /**
          * Description...
         */
        "optionFlow"?: SelectFlowTypes;
        /**
          * Description...
         */
        "options"?: SelectOptionType[];
        /**
          * Description...
         */
        "placeholder"?: string;
        /**
          * Description...
         */
        "toggleFlow"?: SelectFlowTypes;
    }
    interface EzpTextButton {
        /**
          * Description...
         */
        "blank"?: boolean;
        /**
          * Description...
         */
        "disabled"?: boolean;
        /**
          * Description...
         */
        "href"?: string;
        /**
          * Description...
         */
        "level"?: TextButtonLevelTypes;
        /**
          * Description...
         */
        "type"?: TextButtonTypeTypes;
    }
    interface EzpTypoBody {
        /**
          * Description...
         */
        "level"?: TypoBodyLevelTypes;
        /**
          * Description...
         */
        "weight"?: TypoWeightTypes;
    }
    interface EzpTypoHeading {
        /**
          * Description...
         */
        "level"?: TypoHeadingLevelTypes;
        /**
          * Description...
         */
        "tag"?: TypoHeadingTagTypes;
        /**
          * Description...
         */
        "weight"?: TypoWeightTypes;
    }
    interface IntrinsicElements {
        "ezp-auth": EzpAuth;
        "ezp-icon": EzpIcon;
        "ezp-icon-button": EzpIconButton;
        "ezp-printer-selection": EzpPrinterSelection;
        "ezp-printing": EzpPrinting;
        "ezp-progress": EzpProgress;
        "ezp-select": EzpSelect;
        "ezp-text-button": EzpTextButton;
        "ezp-typo-body": EzpTypoBody;
        "ezp-typo-heading": EzpTypoHeading;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ezp-auth": LocalJSX.EzpAuth & JSXBase.HTMLAttributes<HTMLEzpAuthElement>;
            "ezp-icon": LocalJSX.EzpIcon & JSXBase.HTMLAttributes<HTMLEzpIconElement>;
            "ezp-icon-button": LocalJSX.EzpIconButton & JSXBase.HTMLAttributes<HTMLEzpIconButtonElement>;
            "ezp-printer-selection": LocalJSX.EzpPrinterSelection & JSXBase.HTMLAttributes<HTMLEzpPrinterSelectionElement>;
            "ezp-printing": LocalJSX.EzpPrinting & JSXBase.HTMLAttributes<HTMLEzpPrintingElement>;
            "ezp-progress": LocalJSX.EzpProgress & JSXBase.HTMLAttributes<HTMLEzpProgressElement>;
            "ezp-select": LocalJSX.EzpSelect & JSXBase.HTMLAttributes<HTMLEzpSelectElement>;
            "ezp-text-button": LocalJSX.EzpTextButton & JSXBase.HTMLAttributes<HTMLEzpTextButtonElement>;
            "ezp-typo-body": LocalJSX.EzpTypoBody & JSXBase.HTMLAttributes<HTMLEzpTypoBodyElement>;
            "ezp-typo-heading": LocalJSX.EzpTypoHeading & JSXBase.HTMLAttributes<HTMLEzpTypoHeadingElement>;
        }
    }
}
